name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.actor }}
          outputs: dist/snake.svg
      - uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/snake.svg
